/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 342354727
 */
//public class resultPage extends javax.swing.JFrame {

//importing required packages
import java.io.IOException;
import java.io.FileWriter;
import java.io.File;
import java.util.Scanner;
import java.util.ArrayList;

public class resultPage extends javax.swing.JFrame {
    
    /**
     * Creates new form resultPage
     */
    
//    public static ArrayList<User> makeClass(){
//        ArrayList<User> classroom = new ArrayList<>(); // ArrayList of Strings
//        return classroom;
//    }
    
    public resultPage() {
        initComponents();

        //private ArrayList<User> school;
        //displaying current user's score
        resultLabel.setText("You scored "+(studentPage.student).getResult()+"/10");
        
 
        try{
            //adding the current student to the school record
            FileWriter writer = new FileWriter("school.txt",true);
            writer.write("\nstudent;"+studentPage.student.getName()+";"+studentPage.student.getAge()+";"+studentPage.student.getExperience()+";"+studentPage.student.getResult()+";"+studentPage.student.getID()+";"+studentPage.student.getClassCode());
            writer.close();
            
            //making an array of everyone in the school;
            ArrayList<User> school = new ArrayList<>();
            Scanner reader = new Scanner(new File("school.txt"));
            
            //eating the first line of description
            reader.nextLine();
            
            while (reader.hasNextLine()){
                String x = reader.nextLine();
                String data[]= x.split(";");
                
                //if teacher, create instance of the teacher class and add to the polymorphic array
                if(data[0].equals("teacher")){
                    //parsing age and ID into integers
                    int age = Integer.parseInt(data[2]);
                    int ID = Integer.parseInt(data[5]);
                    
                    //instantiating a teacher with the given details
                    Teacher teacher = new Teacher(data[1],age,data[3],ID,data[6]);
                    //adding the teacher to the school array
                    school.add(teacher);
                
                //if student, create instance of rhe stduent class and add to the polymorphic array
                } else if(data[0].equals("student")){
                    //parsing age, id, and result into integers
                    int age = Integer.parseInt(data[2]);
                    int result = Integer.parseInt(data[4]);
                    int ID = Integer.parseInt(data[5]);
                    
                    //instantiating a student with the given details 
                    Student student = new Student(data[1],age,data[3],result,ID,data[6]);
                    //adding the student to the school array
                    school.add(student);
                    
                }
                
            }
            //closing the scanner
            reader.close();
            //TEST
            System.out.print("School: ");
            for (int i=0;i<school.size();i++){
                System.out.println(school.get(i));
            }
            System.out.println("Done printing school");
            
        } catch(IOException e){
            System.out.println("Error"+e);
        }
        
        //displaying the user's score in comparison to their classmates
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        leaderboard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Results");

        resultLabel.setText("jLabel2");

        leaderboard.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultLabel)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(leaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(resultLabel)
                .addGap(45, 45, 45)
                .addComponent(leaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resultPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel leaderboard;
    private javax.swing.JLabel resultLabel;
    // End of variables declaration//GEN-END:variables
}
