/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 342354727
 */

//importing packages
import java.io.IOException;
import java.io.File;
import java.util.Scanner;

public class studentPage extends javax.swing.JFrame {
    private int qNum=1;
    public static int score =0;
    public static String currentAnswer="";
    public static String[] headers;
    public static String[] answers;
    public static String[] explainations;
    public static int lines;
    
    /**
     * Creates new form studentPage
     */
    public studentPage() {
        initComponents();
        lines =0;
        try{
            Scanner lineCounter = new Scanner(new File("Questions.txt"));
            while (lineCounter.hasNextLine()){
                lineCounter.nextLine();
                lines++;
            }
            lineCounter.close();
            //subtracting 1 from the number of lines
            lines-=1;
            //creating my array of healines, answers, and explainations and setting it to the number of lines 
            headers = new String [lines];
            answers = new String[lines];
            explainations = new String[lines];
            
            //adding all of the data to the arrays
            Scanner input = new Scanner(new File("Questions.txt"));
            //skipping the first line
            input.nextLine();
            for (int i =0; i<lines; i++){
                String currentLine = input.nextLine();
                //spliting the lines into the different parts of the question
                String data[] = currentLine.split(";");
                //storing each data piece in respective array
                headers[i]= data[0];
                answers[i]= data[1];
                explainations[i]= data[2];
            }
            input.close();
            
        } catch(IOException e){
            System.out.print(e);
        }
        //counting the lines in my file of questions
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fakeButton = new javax.swing.JButton();
        realButton = new javax.swing.JButton();
        comment = new javax.swing.JLabel();
        headline = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fakeButton.setText("FAKE");
        fakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fakeButtonActionPerformed(evt);
            }
        });

        realButton.setText("REAL");
        realButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realButtonActionPerformed(evt);
            }
        });

        comment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        headline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headline.setText("City Implements Fine for Walking Too Slowly on Busy Sidewalks");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(headline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(realButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headline, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(realButton, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comment, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void realButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realButtonActionPerformed
        //setting users answer to real
        currentAnswer="real";
        
        //checking if the user has the correct answer
        if (qNum==1){
            if (currentAnswer.equals("false")){
                score+=1;
            }
        } else{
            if (currentAnswer.equals(answers[qNum-2])){
                score+=1;
            }
        }
    }//GEN-LAST:event_realButtonActionPerformed

    private void fakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fakeButtonActionPerformed
        //setting current answer to fake
        currentAnswer="fake";
        //checking if the user has the correct answer
        if (qNum==1){
            if (currentAnswer.equals("false")){
                score+=1;
            }
        } else{
            if (currentAnswer.equals(answers[qNum-2])){
                score+=1;
            }
        }
        
        if (qNum!=1&&qNum<=lines+1&&qNum!=11){
                headline.setText(headers[qNum-2]);
            }
    }//GEN-LAST:event_fakeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comment;
    private javax.swing.JButton fakeButton;
    private javax.swing.JLabel headline;
    private javax.swing.JButton realButton;
    // End of variables declaration//GEN-END:variables
}
